# Generated by Django 5.1.1 on 2024-09-30 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ikasle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('abizena', models.CharField(max_length=100)),
                ('jaiotze_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
