# Generated by Django 5.1.1 on 2024-10-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ikasgaia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('maila', models.CharField(max_length=100)),
                ('hizkuntza', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('oharra', models.CharField(max_length=100)),
                ('ikasgaia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.ikasle')),
                ('ikasle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.ikasgaia')),
            ],
        ),
    ]
