# Generated by Django 5.1.2 on 2024-10-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osakidetza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('oharra', models.CharField(max_length=200)),
                ('medikua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osakidetza.medikua')),
                ('pazientea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osakidetza.pazientea')),
            ],
        ),
    ]
