# Generated by Django 5.1.2 on 2024-10-14 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osakidetza', '0002_zita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zita',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
